// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8a8a8a8-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            Description = "Флагманский смартфон с камерой 200 МП",
                            IsAvailable = true,
                            Name = "Смартфон Samsung Galaxy S23",
                            Price = 89990m
                        },
                        new
                        {
                            Id = new Guid("b7b7b7b7-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "b5c6d7e8-f9a0-4b1c-8d2e-3f4a5b6c7d8e",
                            Description = "Игровой ноутбук с RTX 4090",
                            IsAvailable = true,
                            Name = "Ноутбук ASUS ROG Zephyrus",
                            Price = 249990m,
                            UpdatedAt = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c6c6c6c6-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "c9d8e7f6-5a4b-3c2d-1e0f-9a8b7c6d5e4f",
                            Description = "Беспроводные наушники с шумоподавлением",
                            IsAvailable = true,
                            Name = "Наушники Sony WH-1000XM5",
                            Price = 34990m
                        },
                        new
                        {
                            Id = new Guid("d5d5d5d5-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            Description = "Смарт-часы с функцией ЭКГ",
                            IsAvailable = false,
                            Name = "Apple Watch Series 9",
                            Price = 45990m,
                            UpdatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e4e4e4e4-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "e3f4a5b6-c7d8-4e9f-0a1b-2c3d4e5f6a7b",
                            Description = "Зеркальный фотоаппарат 45 МП",
                            IsAvailable = true,
                            Name = "Фотоаппарат Canon EOS R5",
                            Price = 379990m
                        },
                        new
                        {
                            Id = new Guid("f3f3f3f3-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            Description = "Читалка с экраном E Ink Carta",
                            IsAvailable = true,
                            Name = "Электронная книга PocketBook 740",
                            Price = 19990m,
                            UpdatedAt = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a7a7a7a7-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d",
                            Description = "Игровая консоль нового поколения",
                            IsAvailable = true,
                            Name = "PlayStation 5",
                            Price = 79990m
                        },
                        new
                        {
                            Id = new Guid("b6b6b6b6-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d6e",
                            Description = "4K монитор с поддержкой HDR",
                            IsAvailable = false,
                            Name = "Монитор LG UltraFine 32UN880",
                            Price = 89990m,
                            UpdatedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c5c5c5c5-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "3c4d5e6f-7a8b-4c9d-0e1f-2a3b4c5d6e7f",
                            Description = "Беспроводная клавиатура с подсветкой",
                            IsAvailable = true,
                            Name = "Клавиатура Logitech MX Keys",
                            Price = 12990m
                        },
                        new
                        {
                            Id = new Guid("d4d4d4d4-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = "4d5e6f7a-8b9c-4d0e-1f2a-3b4c5d6e7f8a",
                            Description = "Портативный SSD с USB 3.2 Gen 2",
                            IsAvailable = true,
                            Name = "SSD Samsung T7 1TB",
                            Price = 10990m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
